//! # Climate Layer
//!
//! Latitude-based climate system using a sine-wave temperature model with
//! noise-warped latitude boundaries and procedural humidity.
//!
//! The world is divided into **13 climate zones** that repeat every
//! `CLIMATE_BAND_SCALE` blocks along the Z axis:
//!
//! ```text
//! Z ──────────────────────────────────────►
//!   Arctic → Subarctic → N.Temperate → N.Subtropical →
//!   N.Tropical → N.Subequatorial → Equatorial →
//!   S.Subequatorial → S.Tropical → S.Subtropical →
//!   S.Temperate → Subantarctic → Antarctic → repeat...
//! ```
//!
//! Noise is used to warp zone boundaries so they aren't perfectly straight
//! lines, creating more natural-looking climate transitions.
//!
//! ## Usage
//! ```ignore
//! let climate = ClimateLayer::new(42);
//! let info = climate.sample(1024, 8000);
//! println!("Temp: {:.2}, Humidity: {:.2}, Zone: {:?}", info.temperature, info.humidity, info.climate_type);
//! ```

use noise::{NoiseFn, Perlin};
use rayon::prelude::*;
use crate::core::config;
use crate::debug_log;
use crate::flow_debug_log;
// ---------------------------------------------------------------------------
// ClimateType
// ---------------------------------------------------------------------------

/// Climate zone types, ordered from coldest to hottest.
///
/// There are 13 zones total: 6 northern, 1 equatorial, 6 southern.
/// They cycle every `CLIMATE_BAND_SCALE` blocks along Z.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ClimateType {
    /// Polar ice / extreme cold zone.
    Antarctic,
    /// Just outside the polar region; cold but habitable.
    Subantarctic,
    /// Temperate forests and grasslands.
    SouthTemperate,
    /// Warm, dry regions approaching the tropics.
    SouthSubtropical,
    /// Warm tropical zone with monsoon potential.
    SouthTropical,
    /// Transitional zone near the equator.
    SouthSubequatorial,
    /// Hot equatorial band with high humidity potential.
    Equatorial,
    /// Transitional zone near the equator.
    NorthSubequatorial,
    /// Warm tropical zone with monsoon potential.
    NorthTropical,
    /// Warm, dry regions approaching the tropics.
    NorthSubtropical,
    /// Temperate forests and grasslands.
    NorthTemperate,
    /// Just outside the polar region; cold but habitable.
    Subarctic,
    /// Polar ice / extreme cold zone.
    Arctic,
}

impl ClimateType {
    /// Returns a human-readable name for this climate zone.
    pub fn name(&self) -> &'static str {
        match self {
            ClimateType::Antarctic => "Antarctic",
            ClimateType::Subantarctic => "Subantarctic",
            ClimateType::SouthTemperate => "South Temperate",
            ClimateType::SouthSubtropical => "South Subtropical",
            ClimateType::SouthTropical => "South Tropical",
            ClimateType::SouthSubequatorial => "South Subequatorial",
            ClimateType::Equatorial => "Equatorial",
            ClimateType::NorthSubequatorial => "North Subequatorial",
            ClimateType::NorthTropical => "North Tropical",
            ClimateType::NorthSubtropical => "North Subtropical",
            ClimateType::NorthTemperate => "North Temperate",
            ClimateType::Subarctic => "Subarctic",
            ClimateType::Arctic => "Arctic",
        }
    }

    /// Returns true if this zone is in the northern hemisphere (temperature > 0).
    pub fn is_northern(&self) -> bool {
        matches!(
            self,
            ClimateType::Arctic
                | ClimateType::Subarctic
                | ClimateType::NorthTemperate
                | ClimateType::NorthSubtropical
                | ClimateType::NorthTropical
                | ClimateType::NorthSubequatorial
        )
    }

    /// Returns true if this zone is the equatorial band.
    pub fn is_equatorial(&self) -> bool {
        matches!(self, ClimateType::Equatorial)
    }

    /// Returns true if this zone is in the southern hemisphere (temperature < 0).
    pub fn is_southern(&self) -> bool {
        !self.is_northern() && !self.is_equatorial()
    }
}

// ---------------------------------------------------------------------------
// ClimateInfo
// ---------------------------------------------------------------------------

/// Climate information for a given `(x, z)` world position.
///
/// Contains the raw temperature and humidity values as well as the
/// discretized climate zone.
#[derive(Debug, Clone, Copy)]
pub struct ClimateInfo {
    /// Raw temperature: `-1.0` at the poles, `+1.0` at the arctic peak,
    /// `0.0` at the equator.
    ///
    /// Derived from a sine wave with noise-warped latitude boundaries.
    pub temperature: f64,

    /// Humidity: `0.0` (arid desert) to `1.0` (rainforest).
    ///
    /// Generated by independent Perlin noise at medium scale.
    pub humidity: f64,

    /// The discrete climate zone this position belongs to.
    pub climate_type: ClimateType,

    /// Index in the 13-zone cycle (`0..=12`).
    ///
    /// Zone 0 = Arctic, Zone 6 = Equatorial, Zone 12 = Antarctic.
    pub zone_index: u8,
}

// ---------------------------------------------------------------------------
// ClimateLayer
// ---------------------------------------------------------------------------

/// Climate generator producing temperature and humidity data per position.
///
/// Temperature follows a sine-wave model along Z with Perlin noise
/// warping the boundaries between zones. Humidity is independent
/// Perlin noise at medium scale.
///
/// # Thread Safety
/// This type is `Send + Sync` and safe to share across threads.
pub struct ClimateLayer {
    boundary_noise: Perlin,
    humidity_noise: Perlin,
    seed: u64,

    // Config values captured at construction.
    band_scale: f64,
    boundary_noise_scale: f64,
    boundary_warp_amount: f64,
    humidity_noise_scale: f64,
}

impl ClimateLayer {
    /// Creates a new climate layer with the given world seed.
    ///
    /// Sub-seeds:
    /// - `seed + 100` → boundary warping noise
    /// - `seed + 200` → humidity noise
    ///
    /// # Arguments
    /// * `seed` - World seed (any `u64` value).
    pub fn new(seed: u64) -> Self {
        let cfg = &config::world_gen_config().climate;

        debug_log!(
            "ClimateLayer",
            "new",
            "Creating climate layer seed={} band_scale={:.0}",
            seed,
            cfg.band_scale
        );

        let boundary_noise = Perlin::new((seed + 100) as u32);
        let humidity_noise = Perlin::new((seed + 200) as u32);

        Self {
            boundary_noise,
            humidity_noise,
            seed,
            band_scale: cfg.band_scale,
            boundary_noise_scale: cfg.boundary_noise_scale,
            boundary_warp_amount: cfg.boundary_warp_amount,
            humidity_noise_scale: cfg.humidity_noise_scale,
        }
    }

    /// Constructs a climate layer using an explicit config (bypasses global).
    pub fn with_config(seed: u64, cfg: &crate::core::config::ClimateConfig) -> Self {
        let boundary_noise = Perlin::new((seed + 100) as u32);
        let humidity_noise = Perlin::new((seed + 200) as u32);
        Self {
            boundary_noise,
            humidity_noise,
            seed,
            band_scale: cfg.band_scale,
            boundary_noise_scale: cfg.boundary_noise_scale,
            boundary_warp_amount: cfg.boundary_warp_amount,
            humidity_noise_scale: cfg.humidity_noise_scale,
        }
    }

    /// Samples climate information at the given world coordinates.
    ///
    /// # Algorithm
    /// 1. Compute base temperature from a sine wave along Z.
    /// 2. Warp the latitude with low-frequency Perlin noise.
    /// 3. Recompute temperature from the warped latitude.
    /// 4. Generate humidity from independent noise.
    /// 5. Map temperature to one of 13 climate zones.
    ///
    /// # Arguments
    /// * `wx` - World X coordinate (blocks).
    /// * `wz` - World Z coordinate (blocks).
    ///
    /// # Returns
    /// A [`ClimateInfo`] struct with temperature, humidity, and zone data.
    pub fn sample(&self, wx: i32, wz: i32) -> ClimateInfo {
        let base_z = wz as f64;

        let noise_offset = self.boundary_noise.get([
            wx as f64 * self.boundary_noise_scale,
            base_z * self.boundary_noise_scale,
        ]) * self.boundary_warp_amount;

        let warped_z = base_z + noise_offset;

        let phase = (warped_z / self.band_scale) * std::f64::consts::PI * 2.0;
        let temperature = phase.sin();

        let humidity = (self.humidity_noise.get([
            wx as f64 / self.humidity_noise_scale,
            base_z / self.humidity_noise_scale,
        ]) + 1.0)
            * 0.5;

        // --- Climate zone determination ---
        let (climate_type, zone_index) = Self::temperature_to_zone(temperature);

        flow_debug_log!(
            "ClimateLayer",
            "sample",
            "pos=({}, {}) temp={:.3} humidity={:.3} zone={} ({:?})",
            wx,
            wz,
            temperature,
            humidity,
            zone_index,
            climate_type
        );

        ClimateInfo {
            temperature,
            humidity,
            climate_type,
            zone_index,
        }
    }

    /// Samples climate information for a rectangular area (e.g., one chunk).
    ///
    /// Uses Rayon for parallel evaluation. The returned vector is row-major:
    /// index `dz * size + dx`.
    ///
    /// # Arguments
    /// * `cx` - Chunk X index (world start = `cx * size`).
    /// * `cz` - Chunk Z index (world start = `cz * size`).
    /// * `size` - Side length of the square area (typically 16).
    ///
    /// # Returns
    /// A `Vec<ClimateInfo>` with `size * size` elements.
    pub fn sample_area(&self, cx: i32, cz: i32, size: usize) -> Vec<ClimateInfo> {
        flow_debug_log!(
            "ClimateLayer",
            "sample_area",
            "Sampling area chunk=({}, {}) size={}",
            cx,
            cz,
            size
        );

        let start_x = cx * size as i32;
        let start_z = cz * size as i32;
        let total = size * size;

        let results: Vec<ClimateInfo> = (0..total)
            .into_par_iter()
            .map(|i| {
                let dx = (i % size) as i32;
                let dz = (i / size) as i32;
                self.sample(start_x + dx, start_z + dz)
            })
            .collect();

        flow_debug_log!(
            "ClimateLayer",
            "sample_area",
            "Sampled {} positions for chunk ({}, {})",
            results.len(),
            cx,
            cz
        );

        results
    }

    /// Returns the world seed this layer was created with.
    pub fn seed(&self) -> u64 {
        self.seed
    }

    // -----------------------------------------------------------------------
    // Private helpers
    // -----------------------------------------------------------------------

    /// Maps a temperature value to a climate zone and zone index.
    ///
    /// Uses a linear mapping from `[-1.0, 1.0]` to zone indices `[12, 0]`.
    /// The mapping:
    /// - `temp = 1.0`  → zone 0 (Arctic)
    /// - `temp = 0.0`  → zone 6 (Equatorial)
    /// - `temp = -1.0` → zone 12 (Antarctic)
    ///
    /// Formula: `zone_index = floor((1.0 - temperature) * 6.5)` clamped to `[0, 12]`.
    #[inline]
    fn temperature_to_zone(temperature: f64) -> (ClimateType, u8) {
        const ZONES: [ClimateType; 13] = [
            ClimateType::Arctic,            // 0  — temp ≈ 1.0
            ClimateType::Subarctic,         // 1  — temp ≈ 0.846
            ClimateType::NorthTemperate,    // 2  — temp ≈ 0.692
            ClimateType::NorthSubtropical,  // 3  — temp ≈ 0.538
            ClimateType::NorthTropical,     // 4  — temp ≈ 0.385
            ClimateType::NorthSubequatorial,// 5  — temp ≈ 0.231
            ClimateType::Equatorial,        // 6  — temp ≈ 0.077
            ClimateType::SouthSubequatorial,// 7  — temp ≈ -0.077
            ClimateType::SouthTropical,     // 8  — temp ≈ -0.231
            ClimateType::SouthSubtropical,  // 9  — temp ≈ -0.385
            ClimateType::SouthTemperate,    // 10 — temp ≈ -0.538
            ClimateType::Subantarctic,      // 11 — temp ≈ -0.692
            ClimateType::Antarctic,         // 12 — temp ≈ -0.846
        ];

        let raw_index = (1.0 - temperature) * 6.5;
        let zone_index = raw_index.floor().clamp(0.0, 12.0) as u8;
        let climate_type = ZONES[zone_index as usize];

        (climate_type, zone_index)
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_zone_mapping() {
        // Arctic (temp ≈ 1.0)
        let (zone, idx) = ClimateLayer::temperature_to_zone(1.0);
        assert_eq!(zone, ClimateType::Arctic);
        assert_eq!(idx, 0);

        // Equatorial (temp ≈ 0.0)
        let (zone, idx) = ClimateLayer::temperature_to_zone(0.0);
        assert_eq!(zone, ClimateType::Equatorial);
        assert_eq!(idx, 6);

        // Antarctic (temp ≈ -1.0)
        let (zone, idx) = ClimateLayer::temperature_to_zone(-1.0);
        assert_eq!(zone, ClimateType::Antarctic);
        assert_eq!(idx, 12);
    }

    #[test]
    fn test_zone_boundaries() {
        // Just below Arctic boundary
        let (zone, _) = ClimateLayer::temperature_to_zone(0.84);
        assert_eq!(zone, ClimateType::Subarctic);

        // Just above Equatorial (northern side)
        let (zone, _) = ClimateLayer::temperature_to_zone(0.08);
        assert_eq!(zone, ClimateType::NorthSubequatorial);

        // Just below Equatorial (southern side)
        let (zone, _) = ClimateLayer::temperature_to_zone(-0.08);
        assert_eq!(zone, ClimateType::SouthSubequatorial);
    }

    #[test]
    fn test_clamping() {
        // Extremes beyond [-1, 1] should clamp
        let (_, idx_high) = ClimateLayer::temperature_to_zone(2.0);
        assert_eq!(idx_high, 0);

        let (_, idx_low) = ClimateLayer::temperature_to_zone(-2.0);
        assert_eq!(idx_low, 12);
    }

    #[test]
    fn test_humidity_range() {
        let layer = ClimateLayer::new(42);
        for x in 0..50 {
            for z in 0..50 {
                let info = layer.sample(x * 200, z * 200);
                assert!(
                    (0.0..=1.0).contains(&info.humidity),
                    "humidity out of range: {}",
                    info.humidity
                );
            }
        }
    }

    #[test]
    fn test_sample_area_size() {
        let layer = ClimateLayer::new(42);
        let results = layer.sample_area(0, 0, 16);
        assert_eq!(results.len(), 256);
    }

    #[test]
    fn test_deterministic() {
        let layer = ClimateLayer::new(777);
        let a = layer.sample(500, 500);
        let b = layer.sample(500, 500);
        assert_eq!(a.temperature, b.temperature);
        assert_eq!(a.humidity, b.humidity);
        assert_eq!(a.climate_type, b.climate_type);
    }

    #[test]
    fn test_all_zones_present() {
        let layer = ClimateLayer::new(42);
        let mut found = [false; 13];
        // Scan a large area along Z
        for z in 0..32000 {
            let info = layer.sample(0, z);
            found[info.zone_index as usize] = true;
        }
        for (i, &present) in found.iter().enumerate() {
            assert!(present, "Zone {} not found in scan", i);
        }
    }

    #[test]
    fn test_climate_type_properties() {
        assert!(ClimateType::Arctic.is_northern());
        assert!(!ClimateType::Arctic.is_southern());
        assert!(ClimateType::Equatorial.is_equatorial());
        assert!(ClimateType::SouthTropical.is_southern());
        assert!(!ClimateType::SouthTropical.is_northern());
    }
}
